# Generated by Django 5.2.17 on 2026-09-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('menu', 'Menu'), ('submenu', 'SubMenu'), ('page', 'Page'), ('widget', 'Widget')], db_index=True, max_length=20)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drf_dynamic_nav.navigationitem')),
            ],
            options={
                'db_table': 'test_navigation_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_id', models.BigIntegerField(db_index=True, help_text='External Role ID')),
                ('subrole_id', models.BigIntegerField(blank=True, db_index=True, help_text='Optional external SubRole ID', null=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navigation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_permissions', to='drf_dynamic_nav.navigationitem')),
            ],
            options={
                'db_table': 'test_nav_permission',
            },
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(fields=['item_type', 'is_active'], name='idx_nav_item_type_active'),
        ),
        migrations.AddIndex(
            model_name='navigationitem',
            index=models.Index(fields=['parent', 'sort_order'], name='idx_nav_parent_order'),
        ),
        migrations.AddIndex(
            model_name='navpermission',
            index=models.Index(fields=['role_id', 'subrole_id'], name='idx_role_subrole'),
        ),
        migrations.AddIndex(
            model_name='navpermission',
            index=models.Index(fields=['role_id', 'navigation_item'], name='idx_role_navigation'),
        ),
        migrations.AddConstraint(
            model_name='navpermission',
            constraint=models.UniqueConstraint(fields=('role_id', 'subrole_id', 'navigation_item'), name='unique_role_subrole_navigation'),
        ),
    ]
